// File generated by EastAsianWidth.py
#include "unicode_utils.h"

bool unicode_is_wide(uint32_t c) {
    if (c < 4352) {
        return false;
    }
    if (c <= 65091) {
        if (c <= 12336) {
            if (c <= 11929) {
                if (c <= 9962) {
                    if (c <= 9811) {
                        if (c <= 9200) {
                            if (c <= 9002) {
                                if (c <= 9001) {
                                    if (c <= 8987) {
                                        if (c <= 4447) {
                                            return c >= 4352;
                                        } else {
                                            return c >= 8986;
                                        }
                                    } else {
                                        return c >= 9001;
                                    }
                                } else {
                                    return c >= 9002;
                                }
                            } else {
                                if (c <= 9196) {
                                    return c >= 9193;
                                } else {
                                    return c >= 9200;
                                }
                            }
                        } else {
                            if (c <= 9749) {
                                if (c <= 9726) {
                                    if (c <= 9203) {
                                        return c >= 9203;
                                    } else {
                                        return c >= 9725;
                                    }
                                } else {
                                    return c >= 9748;
                                }
                            } else {
                                return c >= 9800;
                            }
                        }
                    } else {
                        if (c <= 9918) {
                            if (c <= 9889) {
                                if (c <= 9875) {
                                    if (c <= 9855) {
                                        return c >= 9855;
                                    } else {
                                        return c >= 9875;
                                    }
                                } else {
                                    return c >= 9889;
                                }
                            } else {
                                if (c <= 9899) {
                                    return c >= 9898;
                                } else {
                                    return c >= 9917;
                                }
                            }
                        } else {
                            if (c <= 9940) {
                                if (c <= 9934) {
                                    if (c <= 9925) {
                                        return c >= 9924;
                                    } else {
                                        return c >= 9934;
                                    }
                                } else {
                                    return c >= 9940;
                                }
                            } else {
                                return c >= 9962;
                            }
                        }
                    }
                } else {
                    if (c <= 10069) {
                        if (c <= 9995) {
                            if (c <= 9981) {
                                if (c <= 9978) {
                                    if (c <= 9973) {
                                        if (c <= 9971) {
                                            return c >= 9970;
                                        } else {
                                            return c >= 9973;
                                        }
                                    } else {
                                        return c >= 9978;
                                    }
                                } else {
                                    return c >= 9981;
                                }
                            } else {
                                if (c <= 9989) {
                                    return c >= 9989;
                                } else {
                                    return c >= 9994;
                                }
                            }
                        } else {
                            if (c <= 10062) {
                                if (c <= 10060) {
                                    if (c <= 10024) {
                                        return c >= 10024;
                                    } else {
                                        return c >= 10060;
                                    }
                                } else {
                                    return c >= 10062;
                                }
                            } else {
                                return c >= 10067;
                            }
                        }
                    } else {
                        if (c <= 11036) {
                            if (c <= 10160) {
                                if (c <= 10135) {
                                    if (c <= 10071) {
                                        return c >= 10071;
                                    } else {
                                        return c >= 10133;
                                    }
                                } else {
                                    return c >= 10160;
                                }
                            } else {
                                if (c <= 10175) {
                                    return c >= 10175;
                                } else {
                                    return c >= 11035;
                                }
                            }
                        } else {
                            if (c <= 11093) {
                                if (c <= 11088) {
                                    return c >= 11088;
                                } else {
                                    return c >= 11093;
                                }
                            } else {
                                return c >= 11904;
                            }
                        }
                    }
                }
            } else {
                if (c <= 12305) {
                    if (c <= 12296) {
                        if (c <= 12292) {
                            if (c <= 12288) {
                                if (c <= 12287) {
                                    if (c <= 12245) {
                                        if (c <= 12019) {
                                            return c >= 11931;
                                        } else {
                                            return c >= 12032;
                                        }
                                    } else {
                                        return c >= 12272;
                                    }
                                } else {
                                    return c >= 12288;
                                }
                            } else {
                                if (c <= 12291) {
                                    return c >= 12289;
                                } else {
                                    return c >= 12292;
                                }
                            }
                        } else {
                            if (c <= 12295) {
                                if (c <= 12294) {
                                    if (c <= 12293) {
                                        return c >= 12293;
                                    } else {
                                        return c >= 12294;
                                    }
                                } else {
                                    return c >= 12295;
                                }
                            } else {
                                return c >= 12296;
                            }
                        }
                    } else {
                        if (c <= 12301) {
                            if (c <= 12299) {
                                if (c <= 12298) {
                                    if (c <= 12297) {
                                        return c >= 12297;
                                    } else {
                                        return c >= 12298;
                                    }
                                } else {
                                    return c >= 12299;
                                }
                            } else {
                                if (c <= 12300) {
                                    return c >= 12300;
                                } else {
                                    return c >= 12301;
                                }
                            }
                        } else {
                            if (c <= 12304) {
                                if (c <= 12303) {
                                    if (c <= 12302) {
                                        return c >= 12302;
                                    } else {
                                        return c >= 12303;
                                    }
                                } else {
                                    return c >= 12304;
                                }
                            } else {
                                return c >= 12305;
                            }
                        }
                    }
                } else {
                    if (c <= 12315) {
                        if (c <= 12311) {
                            if (c <= 12309) {
                                if (c <= 12308) {
                                    if (c <= 12307) {
                                        return c >= 12306;
                                    } else {
                                        return c >= 12308;
                                    }
                                } else {
                                    return c >= 12309;
                                }
                            } else {
                                if (c <= 12310) {
                                    return c >= 12310;
                                } else {
                                    return c >= 12311;
                                }
                            }
                        } else {
                            if (c <= 12314) {
                                if (c <= 12313) {
                                    if (c <= 12312) {
                                        return c >= 12312;
                                    } else {
                                        return c >= 12313;
                                    }
                                } else {
                                    return c >= 12314;
                                }
                            } else {
                                return c >= 12315;
                            }
                        }
                    } else {
                        if (c <= 12329) {
                            if (c <= 12319) {
                                if (c <= 12317) {
                                    if (c <= 12316) {
                                        return c >= 12316;
                                    } else {
                                        return c >= 12317;
                                    }
                                } else {
                                    return c >= 12318;
                                }
                            } else {
                                if (c <= 12320) {
                                    return c >= 12320;
                                } else {
                                    return c >= 12321;
                                }
                            }
                        } else {
                            if (c <= 12335) {
                                if (c <= 12333) {
                                    return c >= 12330;
                                } else {
                                    return c >= 12334;
                                }
                            } else {
                                return c >= 12336;
                            }
                        }
                    }
                }
            }
        } else {
            if (c <= 13055) {
                if (c <= 12686) {
                    if (c <= 12444) {
                        if (c <= 12349) {
                            if (c <= 12347) {
                                if (c <= 12346) {
                                    if (c <= 12343) {
                                        if (c <= 12341) {
                                            return c >= 12337;
                                        } else {
                                            return c >= 12342;
                                        }
                                    } else {
                                        return c >= 12344;
                                    }
                                } else {
                                    return c >= 12347;
                                }
                            } else {
                                if (c <= 12348) {
                                    return c >= 12348;
                                } else {
                                    return c >= 12349;
                                }
                            }
                        } else {
                            if (c <= 12442) {
                                if (c <= 12438) {
                                    if (c <= 12350) {
                                        return c >= 12350;
                                    } else {
                                        return c >= 12353;
                                    }
                                } else {
                                    return c >= 12441;
                                }
                            } else {
                                return c >= 12443;
                            }
                        }
                    } else {
                        if (c <= 12539) {
                            if (c <= 12448) {
                                if (c <= 12447) {
                                    if (c <= 12446) {
                                        return c >= 12445;
                                    } else {
                                        return c >= 12447;
                                    }
                                } else {
                                    return c >= 12448;
                                }
                            } else {
                                if (c <= 12538) {
                                    return c >= 12449;
                                } else {
                                    return c >= 12539;
                                }
                            }
                        } else {
                            if (c <= 12591) {
                                if (c <= 12543) {
                                    if (c <= 12542) {
                                        return c >= 12540;
                                    } else {
                                        return c >= 12543;
                                    }
                                } else {
                                    return c >= 12549;
                                }
                            } else {
                                return c >= 12593;
                            }
                        }
                    }
                } else {
                    if (c <= 12841) {
                        if (c <= 12771) {
                            if (c <= 12703) {
                                if (c <= 12693) {
                                    if (c <= 12689) {
                                        return c >= 12688;
                                    } else {
                                        return c >= 12690;
                                    }
                                } else {
                                    return c >= 12694;
                                }
                            } else {
                                if (c <= 12735) {
                                    return c >= 12704;
                                } else {
                                    return c >= 12736;
                                }
                            }
                        } else {
                            if (c <= 12830) {
                                if (c <= 12799) {
                                    if (c <= 12783) {
                                        return c >= 12783;
                                    } else {
                                        return c >= 12784;
                                    }
                                } else {
                                    return c >= 12800;
                                }
                            } else {
                                return c >= 12832;
                            }
                        }
                    } else {
                        if (c <= 12937) {
                            if (c <= 12895) {
                                if (c <= 12880) {
                                    if (c <= 12871) {
                                        return c >= 12842;
                                    } else {
                                        return c >= 12880;
                                    }
                                } else {
                                    return c >= 12881;
                                }
                            } else {
                                if (c <= 12927) {
                                    return c >= 12896;
                                } else {
                                    return c >= 12928;
                                }
                            }
                        } else {
                            if (c <= 12991) {
                                if (c <= 12976) {
                                    return c >= 12938;
                                } else {
                                    return c >= 12977;
                                }
                            } else {
                                return c >= 12992;
                            }
                        }
                    }
                }
            } else {
                if (c <= 65072) {
                    if (c <= 64109) {
                        if (c <= 42124) {
                            if (c <= 40980) {
                                if (c <= 40959) {
                                    if (c <= 19903) {
                                        if (c <= 13311) {
                                            return c >= 13056;
                                        } else {
                                            return c >= 13312;
                                        }
                                    } else {
                                        return c >= 19968;
                                    }
                                } else {
                                    return c >= 40960;
                                }
                            } else {
                                if (c <= 40981) {
                                    return c >= 40981;
                                } else {
                                    return c >= 40982;
                                }
                            }
                        } else {
                            if (c <= 55203) {
                                if (c <= 43388) {
                                    if (c <= 42182) {
                                        return c >= 42128;
                                    } else {
                                        return c >= 43360;
                                    }
                                } else {
                                    return c >= 44032;
                                }
                            } else {
                                return c >= 63744;
                            }
                        }
                    } else {
                        if (c <= 65047) {
                            if (c <= 64255) {
                                if (c <= 64217) {
                                    if (c <= 64111) {
                                        return c >= 64110;
                                    } else {
                                        return c >= 64112;
                                    }
                                } else {
                                    return c >= 64218;
                                }
                            } else {
                                if (c <= 65046) {
                                    return c >= 65040;
                                } else {
                                    return c >= 65047;
                                }
                            }
                        } else {
                            if (c <= 65049) {
                                if (c <= 65048) {
                                    return c >= 65048;
                                } else {
                                    return c >= 65049;
                                }
                            } else {
                                return c >= 65072;
                            }
                        }
                    }
                } else {
                    if (c <= 65083) {
                        if (c <= 65079) {
                            if (c <= 65077) {
                                if (c <= 65076) {
                                    if (c <= 65074) {
                                        return c >= 65073;
                                    } else {
                                        return c >= 65075;
                                    }
                                } else {
                                    return c >= 65077;
                                }
                            } else {
                                if (c <= 65078) {
                                    return c >= 65078;
                                } else {
                                    return c >= 65079;
                                }
                            }
                        } else {
                            if (c <= 65082) {
                                if (c <= 65081) {
                                    if (c <= 65080) {
                                        return c >= 65080;
                                    } else {
                                        return c >= 65081;
                                    }
                                } else {
                                    return c >= 65082;
                                }
                            } else {
                                return c >= 65083;
                            }
                        }
                    } else {
                        if (c <= 65088) {
                            if (c <= 65086) {
                                if (c <= 65085) {
                                    if (c <= 65084) {
                                        return c >= 65084;
                                    } else {
                                        return c >= 65085;
                                    }
                                } else {
                                    return c >= 65086;
                                }
                            } else {
                                if (c <= 65087) {
                                    return c >= 65087;
                                } else {
                                    return c >= 65088;
                                }
                            }
                        } else {
                            if (c <= 65090) {
                                if (c <= 65089) {
                                    return c >= 65089;
                                } else {
                                    return c >= 65090;
                                }
                            } else {
                                return c >= 65091;
                            }
                        }
                    }
                }
            }
        }
    } else {
        if (c <= 110933) {
            if (c <= 65338) {
                if (c <= 65126) {
                    if (c <= 65113) {
                        if (c <= 65103) {
                            if (c <= 65096) {
                                if (c <= 65095) {
                                    if (c <= 65094) {
                                        if (c <= 65092) {
                                            return c >= 65092;
                                        } else {
                                            return c >= 65093;
                                        }
                                    } else {
                                        return c >= 65095;
                                    }
                                } else {
                                    return c >= 65096;
                                }
                            } else {
                                if (c <= 65100) {
                                    return c >= 65097;
                                } else {
                                    return c >= 65101;
                                }
                            }
                        } else {
                            if (c <= 65112) {
                                if (c <= 65111) {
                                    if (c <= 65106) {
                                        return c >= 65104;
                                    } else {
                                        return c >= 65108;
                                    }
                                } else {
                                    return c >= 65112;
                                }
                            } else {
                                return c >= 65113;
                            }
                        }
                    } else {
                        if (c <= 65118) {
                            if (c <= 65116) {
                                if (c <= 65115) {
                                    if (c <= 65114) {
                                        return c >= 65114;
                                    } else {
                                        return c >= 65115;
                                    }
                                } else {
                                    return c >= 65116;
                                }
                            } else {
                                if (c <= 65117) {
                                    return c >= 65117;
                                } else {
                                    return c >= 65118;
                                }
                            }
                        } else {
                            if (c <= 65123) {
                                if (c <= 65122) {
                                    if (c <= 65121) {
                                        return c >= 65119;
                                    } else {
                                        return c >= 65122;
                                    }
                                } else {
                                    return c >= 65123;
                                }
                            } else {
                                return c >= 65124;
                            }
                        }
                    }
                } else {
                    if (c <= 65291) {
                        if (c <= 65287) {
                            if (c <= 65283) {
                                if (c <= 65131) {
                                    if (c <= 65129) {
                                        if (c <= 65128) {
                                            return c >= 65128;
                                        } else {
                                            return c >= 65129;
                                        }
                                    } else {
                                        return c >= 65130;
                                    }
                                } else {
                                    return c >= 65281;
                                }
                            } else {
                                if (c <= 65284) {
                                    return c >= 65284;
                                } else {
                                    return c >= 65285;
                                }
                            }
                        } else {
                            if (c <= 65290) {
                                if (c <= 65289) {
                                    if (c <= 65288) {
                                        return c >= 65288;
                                    } else {
                                        return c >= 65289;
                                    }
                                } else {
                                    return c >= 65290;
                                }
                            } else {
                                return c >= 65291;
                            }
                        }
                    } else {
                        if (c <= 65307) {
                            if (c <= 65295) {
                                if (c <= 65293) {
                                    if (c <= 65292) {
                                        return c >= 65292;
                                    } else {
                                        return c >= 65293;
                                    }
                                } else {
                                    return c >= 65294;
                                }
                            } else {
                                if (c <= 65305) {
                                    return c >= 65296;
                                } else {
                                    return c >= 65306;
                                }
                            }
                        } else {
                            if (c <= 65312) {
                                if (c <= 65310) {
                                    return c >= 65308;
                                } else {
                                    return c >= 65311;
                                }
                            } else {
                                return c >= 65313;
                            }
                        }
                    }
                }
            } else {
                if (c <= 65510) {
                    if (c <= 65373) {
                        if (c <= 65344) {
                            if (c <= 65342) {
                                if (c <= 65341) {
                                    if (c <= 65340) {
                                        if (c <= 65339) {
                                            return c >= 65339;
                                        } else {
                                            return c >= 65340;
                                        }
                                    } else {
                                        return c >= 65341;
                                    }
                                } else {
                                    return c >= 65342;
                                }
                            } else {
                                if (c <= 65343) {
                                    return c >= 65343;
                                } else {
                                    return c >= 65344;
                                }
                            }
                        } else {
                            if (c <= 65372) {
                                if (c <= 65371) {
                                    if (c <= 65370) {
                                        return c >= 65345;
                                    } else {
                                        return c >= 65371;
                                    }
                                } else {
                                    return c >= 65372;
                                }
                            } else {
                                return c >= 65373;
                            }
                        }
                    } else {
                        if (c <= 65506) {
                            if (c <= 65376) {
                                if (c <= 65375) {
                                    if (c <= 65374) {
                                        return c >= 65374;
                                    } else {
                                        return c >= 65375;
                                    }
                                } else {
                                    return c >= 65376;
                                }
                            } else {
                                if (c <= 65505) {
                                    return c >= 65504;
                                } else {
                                    return c >= 65506;
                                }
                            }
                        } else {
                            if (c <= 65508) {
                                if (c <= 65507) {
                                    return c >= 65507;
                                } else {
                                    return c >= 65508;
                                }
                            } else {
                                return c >= 65509;
                            }
                        }
                    }
                } else {
                    if (c <= 101640) {
                        if (c <= 94193) {
                            if (c <= 94179) {
                                if (c <= 94178) {
                                    if (c <= 94177) {
                                        return c >= 94176;
                                    } else {
                                        return c >= 94178;
                                    }
                                } else {
                                    return c >= 94179;
                                }
                            } else {
                                if (c <= 94180) {
                                    return c >= 94180;
                                } else {
                                    return c >= 94192;
                                }
                            }
                        } else {
                            if (c <= 101589) {
                                if (c <= 101119) {
                                    if (c <= 100343) {
                                        return c >= 94208;
                                    } else {
                                        return c >= 100352;
                                    }
                                } else {
                                    return c >= 101120;
                                }
                            } else {
                                return c >= 101632;
                            }
                        }
                    } else {
                        if (c <= 110882) {
                            if (c <= 110590) {
                                if (c <= 110587) {
                                    if (c <= 110579) {
                                        return c >= 110576;
                                    } else {
                                        return c >= 110581;
                                    }
                                } else {
                                    return c >= 110589;
                                }
                            } else {
                                if (c <= 110847) {
                                    return c >= 110592;
                                } else {
                                    return c >= 110848;
                                }
                            }
                        } else {
                            if (c <= 110930) {
                                if (c <= 110898) {
                                    return c >= 110898;
                                } else {
                                    return c >= 110928;
                                }
                            } else {
                                return c >= 110933;
                            }
                        }
                    }
                }
            }
        } else {
            if (c <= 128727) {
                if (c <= 127988) {
                    if (c <= 127569) {
                        if (c <= 127386) {
                            if (c <= 127183) {
                                if (c <= 126980) {
                                    if (c <= 111355) {
                                        if (c <= 110951) {
                                            return c >= 110948;
                                        } else {
                                            return c >= 110960;
                                        }
                                    } else {
                                        return c >= 126980;
                                    }
                                } else {
                                    return c >= 127183;
                                }
                            } else {
                                if (c <= 127374) {
                                    return c >= 127374;
                                } else {
                                    return c >= 127377;
                                }
                            }
                        } else {
                            if (c <= 127560) {
                                if (c <= 127547) {
                                    if (c <= 127490) {
                                        return c >= 127488;
                                    } else {
                                        return c >= 127504;
                                    }
                                } else {
                                    return c >= 127552;
                                }
                            } else {
                                return c >= 127568;
                            }
                        }
                    } else {
                        if (c <= 127891) {
                            if (c <= 127797) {
                                if (c <= 127776) {
                                    if (c <= 127589) {
                                        return c >= 127584;
                                    } else {
                                        return c >= 127744;
                                    }
                                } else {
                                    return c >= 127789;
                                }
                            } else {
                                if (c <= 127868) {
                                    return c >= 127799;
                                } else {
                                    return c >= 127870;
                                }
                            }
                        } else {
                            if (c <= 127984) {
                                if (c <= 127955) {
                                    if (c <= 127946) {
                                        return c >= 127904;
                                    } else {
                                        return c >= 127951;
                                    }
                                } else {
                                    return c >= 127968;
                                }
                            } else {
                                return c >= 127988;
                            }
                        }
                    }
                } else {
                    if (c <= 128378) {
                        if (c <= 128252) {
                            if (c <= 128062) {
                                if (c <= 127999) {
                                    if (c <= 127994) {
                                        return c >= 127992;
                                    } else {
                                        return c >= 127995;
                                    }
                                } else {
                                    return c >= 128000;
                                }
                            } else {
                                if (c <= 128064) {
                                    return c >= 128064;
                                } else {
                                    return c >= 128066;
                                }
                            }
                        } else {
                            if (c <= 128359) {
                                if (c <= 128334) {
                                    if (c <= 128317) {
                                        return c >= 128255;
                                    } else {
                                        return c >= 128331;
                                    }
                                } else {
                                    return c >= 128336;
                                }
                            } else {
                                return c >= 128378;
                            }
                        }
                    } else {
                        if (c <= 128709) {
                            if (c <= 128511) {
                                if (c <= 128420) {
                                    if (c <= 128406) {
                                        return c >= 128405;
                                    } else {
                                        return c >= 128420;
                                    }
                                } else {
                                    return c >= 128507;
                                }
                            } else {
                                if (c <= 128591) {
                                    return c >= 128512;
                                } else {
                                    return c >= 128640;
                                }
                            }
                        } else {
                            if (c <= 128722) {
                                if (c <= 128716) {
                                    return c >= 128716;
                                } else {
                                    return c >= 128720;
                                }
                            } else {
                                return c >= 128725;
                            }
                        }
                    }
                }
            } else {
                if (c <= 177977) {
                    if (c <= 129672) {
                        if (c <= 129338) {
                            if (c <= 129003) {
                                if (c <= 128764) {
                                    if (c <= 128748) {
                                        if (c <= 128735) {
                                            return c >= 128732;
                                        } else {
                                            return c >= 128747;
                                        }
                                    } else {
                                        return c >= 128756;
                                    }
                                } else {
                                    return c >= 128992;
                                }
                            } else {
                                if (c <= 129008) {
                                    return c >= 129008;
                                } else {
                                    return c >= 129292;
                                }
                            }
                        } else {
                            if (c <= 129660) {
                                if (c <= 129535) {
                                    if (c <= 129349) {
                                        return c >= 129340;
                                    } else {
                                        return c >= 129351;
                                    }
                                } else {
                                    return c >= 129648;
                                }
                            } else {
                                return c >= 129664;
                            }
                        }
                    } else {
                        if (c <= 129784) {
                            if (c <= 129755) {
                                if (c <= 129733) {
                                    if (c <= 129725) {
                                        return c >= 129680;
                                    } else {
                                        return c >= 129727;
                                    }
                                } else {
                                    return c >= 129742;
                                }
                            } else {
                                if (c <= 129768) {
                                    return c >= 129760;
                                } else {
                                    return c >= 129776;
                                }
                            }
                        } else {
                            if (c <= 173823) {
                                if (c <= 173791) {
                                    return c >= 131072;
                                } else {
                                    return c >= 173792;
                                }
                            } else {
                                return c >= 173824;
                            }
                        }
                    }
                } else {
                    if (c <= 194559) {
                        if (c <= 183983) {
                            if (c <= 178207) {
                                if (c <= 178205) {
                                    if (c <= 177983) {
                                        return c >= 177978;
                                    } else {
                                        return c >= 177984;
                                    }
                                } else {
                                    return c >= 178206;
                                }
                            } else {
                                if (c <= 183969) {
                                    return c >= 178208;
                                } else {
                                    return c >= 183970;
                                }
                            }
                        } else {
                            if (c <= 192093) {
                                if (c <= 191471) {
                                    if (c <= 191456) {
                                        return c >= 183984;
                                    } else {
                                        return c >= 191457;
                                    }
                                } else {
                                    return c >= 191472;
                                }
                            } else {
                                return c >= 192094;
                            }
                        }
                    } else {
                        if (c <= 201546) {
                            if (c <= 196605) {
                                if (c <= 195103) {
                                    if (c <= 195101) {
                                        return c >= 194560;
                                    } else {
                                        return c >= 195102;
                                    }
                                } else {
                                    return c >= 195104;
                                }
                            } else {
                                return c >= 196608;
                            }
                        } else {
                            if (c <= 205743) {
                                if (c <= 201551) {
                                    return c >= 201547;
                                } else {
                                    return c >= 201552;
                                }
                            } else {
                                return c <= 262141 && c >= 205744;
                            }
                        }
                    }
                }
            }
        }
    }
}
